"""State definitions for DevPilot LangGraph Agent."""
from typing import TypedDict, Any, Optional
from pydantic import BaseModel, Field


class AnalyzedIssue(BaseModel):
    """Structured representation of a triaged GitHub issue."""
    id: int
    number: int
    title: str
    body: str = ""
    html_url: str = ""
    author: str = ""
    labels: list[str] = Field(default_factory=list)
    file_path: Optional[str] = None
    severity: str = "LOW"  # CRITICAL, HIGH, MEDIUM, LOW
    is_actionable: bool = False
    reason: str = ""
    jira_ticket_key: Optional[str] = None
    pull_request_number: Optional[int] = None


class CodePatch(BaseModel):
    """Code modification patch generated by the AI Software Engineer."""
    file_path: str
    diff: str
    explanation: str
    github_issue_number: Optional[int] = None


class PullRequestResult(BaseModel):
    """Created Pull Request result."""
    number: int
    title: str
    html_url: str
    head_branch: str
    base_branch: str = "main"


class JiraTicketResult(BaseModel):
    """Result of Jira issue creation."""
    key: str
    summary: str
    issue_type: str = "Bug"
    priority: str = "High"
    github_issue_number: int
    pull_request_number: Optional[int] = None
    url: str = ""
    status: str = "Created"


class SlackNotificationResult(BaseModel):
    """Result of Slack notification delivery."""
    channel: str
    ts: str = ""
    summary: str
    delivered: bool = True
    message_text: str = ""


class DevPilotState(TypedDict, total=False):
    """LangGraph state schema for DevPilot workflow."""
    user_request: str
    task_type: str  # 'bug_fix', 'feature_development', 'issue_triage'
    intent: dict[str, Any]
    plan: list[str]
    selected_tools: list[str]
    repo_owner: str
    repo_name: str
    github_username: str
    jira_project: str
    slack_channel: str
    app_mode: str  # 'real' or 'mock'
    github_results: list[dict[str, Any]]
    analyzed_issues: list[dict[str, Any]]
    actionable_issues: list[dict[str, Any]]
    inspected_files: list[dict[str, Any]]
    code_patches: list[dict[str, Any]]
    pull_requests: list[dict[str, Any]]
    jira_results: list[dict[str, Any]]
    slack_results: list[dict[str, Any]]
    actions_taken: list[str]
    decisions: list[str]
    errors: list[str]
    final_response: str
